import { mkdirSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { serializeStoryConfig } from "@/lib/config-io";
import type { StoryConfig } from "@/types/story-config";


/**
 * v0.2.0 输出（§56）：每次生成保存三件套 ——
 *   <stamp>_story.md            正文（含 metadata 引用块）
 *   <stamp>_story.config.json   当时使用的 StoryConfig 快照（§57 可追溯性）
 *   <stamp>_story.meta.json     基本元数据（§54）
 * 文件名不含用户输入（服务端时间戳 + 固定后缀）。这不是 Run Tracking（§55）。
 */
export interface StoryRunMeta {
  project_version: string;
  model: string;
  generated_at: string;
  config_file?: string;
}

export async function saveStoryWithSnapshot(
  config: StoryConfig,
  content: string,
  meta: Omit<StoryRunMeta, "config_file">,
): Promise<{ mdPath: string; configPath: string; metaPath: string }> {
  const dir = join(process.cwd(), "outputs");
  mkdirSync(dir, { recursive: true });
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  const stamp = `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}_${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;

  const mdPath = join(dir, `${stamp}_story.md`);
  const md = `# ${config.title}

> Genre: ${config.genre}  
> Target Words: ${config.target_words}${config.style ? `  \n> Style: ${config.style}` : ""}

${content}

---
Generated by Short Story Generator v0.2.0
`;
  await writeFile(mdPath, md, "utf8");

  const configPath = join(dir, `${stamp}_story.config.json`);
  await writeFile(configPath, serializeStoryConfig(config), "utf8");

  const metaPath = join(dir, `${stamp}_story.meta.json`);
  const fullMeta: StoryRunMeta = { ...meta, config_file: configPath };
  await writeFile(metaPath, JSON.stringify(fullMeta, null, 2), "utf8");

  return { mdPath, configPath, metaPath };
}
