import { mkdirSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";

/**
 * §21/§22 生成成功后保存 Markdown + metadata sidecar（§43）。
 * 文件名仅由服务端时间戳构成（不含任何用户输入），标题与元数据写入文件内容。
 * 不是 Run Artifact System（无 run_id/manifest，§44）。
 */
export interface StoryMeta {
  title: string;
  genre: string;
  premise: string;
  target_words: number;
  style?: string;
  extra_requirements?: string;
  model: string;
  created_at: string;
}

export async function saveStoryWithMeta(
  story: { title: string; content: string },
  meta: StoryMeta,
): Promise<{ mdPath: string; jsonPath: string }> {
  const dir = join(process.cwd(), "outputs");
  mkdirSync(dir, { recursive: true });
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  const stamp = `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}_${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;

  const mdPath = join(dir, `${stamp}_story.md`);
  const md = `# ${story.title}

> Genre: ${meta.genre}  
> Target Words: ${meta.target_words}${meta.style ? `  \n> Style: ${meta.style}` : ""}

${story.content}

---
Generated by Short Story Generator v0.1.0
`;
  await writeFile(mdPath, md, "utf8");

  const jsonPath = join(dir, `${stamp}_story.json`);
  await writeFile(jsonPath, JSON.stringify(meta, null, 2), "utf8");

  return { mdPath, jsonPath };
}
