import fs from "node:fs";
import { join } from "node:path";

/**
 * §21/§22 生成成功后保存 Markdown，返回文件路径。
 * 文件名仅由服务端时间戳构成（不含任何用户输入），标题写入文件内容首行。
 * 目录固定为项目下 outputs/（无环境变量开关）。
 */
export async function saveStory(title: string, content: string): Promise<string> {
  const dir = join(process.cwd(), "outputs");
  fs.mkdirSync(dir, { recursive: true });
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  const stamp = `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}_${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
  const file = `${dir}/${stamp}.md`;
  const body = `# ${title}

${content}

---
Generated by Short Story Generator v0.0.1
`;
  fs.writeFileSync(file, body, "utf8");
  return file;
}
